# Copyright (c) 2026 Xavier Lee <kokteng1313@gmail.com>
# SPDX-License-Identifier: MIT

# Doxygen integration.
#
#   cmake --build build --target docs         -- generate HTML into build/docs/html
#   cmake --build build --target docs-check   -- fail on any undocumented public symbol,
#                                                parameter or return value
#
# The Doxyfile is generated by CMake's doxygen_add_docs() rather than kept in
# the tree, so it always matches the tags understood by the doxygen that was
# actually found instead of drifting against a hand-maintained template.

find_package(Doxygen QUIET)

if(NOT DOXYGEN_FOUND)
    message(STATUS "doxygen not found; `docs` targets unavailable.")
    return()
endif()

# Only the public interface is documented. src/ holds the implementation and
# src/haidi_decode.hpp is internal; private class members are excluded by
# Doxygen's own EXTRACT_PRIVATE default of NO.
set(HAIDI_DOXYGEN_INPUT
    "${CMAKE_SOURCE_DIR}/include"
    "${CMAKE_SOURCE_DIR}/docs/mainpage.dox"
)

set(DOXYGEN_PROJECT_NAME "haidi_bms_cpp")
set(DOXYGEN_PROJECT_BRIEF "Asynchronous driver for HAIDI BMS units over UART/RS485/CAN")
set(DOXYGEN_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/docs")

# EXTRACT_ALL would manufacture empty pages for undocumented symbols and hide
# the very gaps WARN_IF_UNDOCUMENTED exists to report. The pair below is the
# enforcement; leave them together. WARN_NO_PARAMDOC extends it from "every
# symbol has a comment" to "every parameter and return value is described".
set(DOXYGEN_EXTRACT_ALL NO)
set(DOXYGEN_WARN_IF_UNDOCUMENTED YES)
set(DOXYGEN_WARN_NO_PARAMDOC YES)
set(DOXYGEN_WARN_IF_DOC_ERROR YES)

set(DOXYGEN_QUIET YES)
set(DOXYGEN_GENERATE_LATEX NO)
set(DOXYGEN_GENERATE_HTML YES)
set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
set(DOXYGEN_MARKDOWN_SUPPORT YES)
set(DOXYGEN_HAVE_DOT ${DOXYGEN_DOT_FOUND})

# Declaration order carries meaning here: DataId reads in protocol order, and
# the poll_*() methods are grouped by command family.
set(DOXYGEN_SORT_MEMBER_DOCS NO)
set(DOXYGEN_SORT_BRIEF_DOCS NO)

set(DOXYGEN_STRIP_FROM_PATH "${CMAKE_SOURCE_DIR}")
set(DOXYGEN_STRIP_FROM_INC_PATH "${CMAKE_SOURCE_DIR}/include")

# `docs` reports problems, `docs-check` fails on them. Same inputs otherwise.
set(DOXYGEN_WARN_AS_ERROR NO)
doxygen_add_docs(docs ${HAIDI_DOXYGEN_INPUT}
    COMMENT "Generating API documentation with Doxygen"
)

set(DOXYGEN_WARN_AS_ERROR FAIL_ON_WARNINGS)
doxygen_add_docs(docs-check ${HAIDI_DOXYGEN_INPUT}
    COMMENT "Checking that every public symbol is documented"
)
